language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Install required php packages
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash

before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make vih_dk.build ../vih.dk
  - cd ../vih.dk
  - sudo chmod -R 777 sites/all/modules
  - drush si vih_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush cc all --yes

script: drush test-run 'Example Tests' --uri=http://127.0.0.1:8080